# Generated by Django 5.2.1 on 2025-06-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='response',
            name='tendency_score',
        ),
        migrations.AddField(
            model_name='chat',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='봇 / 사용자의 답변 여부 (model, user)'),
        ),
        migrations.AddField(
            model_name='chat',
            name='token_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='AI가 사용한 토큰 개수'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='보고서 작성 시 LLM 프롬프트에 포함될 질문의 의미와 배경 설명', null=True, verbose_name='질문 해설'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('political', '정치 성향'), ('urgent', '중요 현안')], default='political', max_length=20, verbose_name='질문 타입'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_vector',
            field=models.JSONField(blank=True, help_text='1~5번 응답별 성향 점수 [매우동의, 동의, 보통, 비동의, 매우비동의] 순서', null=True, verbose_name='성향 점수 벡터'),
        ),
        migrations.AlterField(
            model_name='politicianreport',
            name='politicians_bottom',
            field=models.JSONField(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='하위 정치인 BOTTOM 10'),
        ),
        migrations.AlterField(
            model_name='politicianreport',
            name='politicians_top',
            field=models.JSONField(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='상위 정치인 TOP 10'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.IntegerField(choices=[(1, '매우동의/매우중요'), (2, '동의/중요'), (3, '보통'), (4, '비동의/덜중요'), (5, '매우비동의/안중요')], verbose_name='객관식 답변'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer_text',
            field=models.TextField(blank=True, help_text='1~10의 자연수를 입력하면 해당 숫자가 가중치로 사용됩니다', verbose_name='서술형 답변'),
        ),
        migrations.AlterField(
            model_name='stance',
            name='politician',
            field=models.ForeignKey(db_column='str_id', on_delete=django.db.models.deletion.CASCADE, related_name='stances', to='main.politician', to_field='str_id', verbose_name='국회의원'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='parties_rank',
            field=models.JSONField(blank=True, default=list, help_text='rank, logo, name, similarity, reason 포함', null=True, verbose_name='정당 랭킹'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='politicians_bottom',
            field=models.JSONField(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='하위 정치인 BOTTOM 10'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='politicians_top',
            field=models.JSONField(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='상위 정치인 TOP 10'),
        ),
    ]
