# Generated by Django 5.2.1 on 2025-06-05 15:51

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianreport',
            name='politicians_bottom',
            field=main.models.JSONFieldV2(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='하위 정치인 BOTTOM 10'),
        ),
        migrations.AlterField(
            model_name='politicianreport',
            name='politicians_top',
            field=main.models.JSONFieldV2(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='상위 정치인 TOP 10'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_vector',
            field=main.models.JSONFieldV2(blank=True, help_text='1~5번 응답별 성향 점수 [매우동의, 동의, 보통, 비동의, 매우비동의] 순서', null=True, verbose_name='성향 점수 벡터'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='parties_rank',
            field=main.models.JSONFieldV2(blank=True, default=list, help_text='rank, logo, name, similarity, reason 포함', null=True, verbose_name='정당 랭킹'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='politicians_bottom',
            field=main.models.JSONFieldV2(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='하위 정치인 BOTTOM 10'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='politicians_top',
            field=main.models.JSONFieldV2(blank=True, default=list, help_text='rank, picture, name, birth, party, similarity, reason 포함', null=True, verbose_name='상위 정치인 TOP 10'),
        ),
    ]
