# Generated by Django 5.2.1 on 2025-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stance_politician'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='politician_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='대화하고 있는 정치인 id'),
        ),
    ]
